[Configuration]
Version = 100

[[Component]]
Path = "example_general_component.sdv"
Class = "Hello_Component"

[[Component]]
Path = "example_general_component.sdv"
Class = "Hello_Component"
number = 42

