[Configuration]
Version = 100

[[Component]]
Path = "simulation_task_timer.sdv"
Class = "SimulationTaskTimerService"

[[Component]]
Path = "tasktimer_component_example.sdv"
Class = "Timer_Example"
Timer = 175


