[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforlongdouble_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.LongDouble_Device"

[[Component]]
Path = "testcase4_bs_rxclassforlongdouble_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.LongDouble_Service"
