[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforlonglong_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.LongLong_Device"

[[Component]]
Path = "testcase4_bs_rxclassforlonglong_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.LongLong_Service"
