[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforu8string_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.U8String_Device"

[[Component]]
Path = "testcase4_bs_rxclassforu8string_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.U8String_Service"
