[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforunsignedshort_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.UnsignedShort_Device"

[[Component]]
Path = "testcase4_bs_rxclassforunsignedshort_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.UnsignedShort_Service"
