[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforunsignedlonglong_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.UnsignedLongLong_Device"

[[Component]]
Path = "testcase4_bs_rxclassforunsignedlonglong_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.UnsignedLongLong_Service"
