[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforchar_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char_Device"

[[Component]]
Path = "testcase4_bs_rxclassforchar_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char_Service"
