[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforu32string_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.U32String_Device"

[[Component]]
Path = "testcase4_bs_rxclassforu32string_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.U32String_Service"
