[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforuint32_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Uint32_Device"

[[Component]]
Path = "testcase4_bs_rxclassforuint32_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Uint32_Service"
