[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforchar16_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char16_Device"

[[Component]]
Path = "testcase4_bs_rxclassforchar16_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char16_Service"
