[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforunsignedlong_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.UnsignedLong_Device"

[[Component]]
Path = "testcase4_bs_rxclassforunsignedlong_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.UnsignedLong_Service"
