[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforchar32_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char32_Device"

[[Component]]
Path = "testcase4_bs_rxclassforchar32_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char32_Service"
