[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforstring_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.String_Device"

[[Component]]
Path = "testcase4_bs_rxclassforstring_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.String_Service"
