[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforshort_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Short_Device"

[[Component]]
Path = "testcase4_bs_rxclassforshort_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Short_Service"
