[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforint64_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Int64_Device"

[[Component]]
Path = "testcase4_bs_rxclassforint64_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Int64_Service"
