[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassfordouble_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Double_Device"

[[Component]]
Path = "testcase4_bs_rxclassfordouble_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Double_Service"
