[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassfornative_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Native_Device"

[[Component]]
Path = "testcase4_bs_rxclassfornative_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Native_Service"
