[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforu16string_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.U16String_Device"

[[Component]]
Path = "testcase4_bs_rxclassforu16string_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.U16String_Service"
