[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforuint8_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Uint8_Device"

[[Component]]
Path = "testcase4_bs_rxclassforuint8_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Uint8_Service"
