[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_rxclassforint8_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Int8_Device"

[[Component]]
Path = "testcase4_bs_rxclassforint8_rx.sdv"
Class = "Vehicle.Chassis.Vehicle.Int8_Service"
