[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforuint16_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Uint16_Device"

[[Component]]
Path = "testcase4_bs_txclassforuint16_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Uint16_Service"
