[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforchar16_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char16_Device"

[[Component]]
Path = "testcase4_bs_txclassforchar16_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char16_Service"
