[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforlong_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Long_Device"

[[Component]]
Path = "testcase4_bs_txclassforlong_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Long_Service"
