[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforu32string_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.U32String_Device"

[[Component]]
Path = "testcase4_bs_txclassforu32string_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.U32String_Service"
