[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforwstring_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.WString_Device"

[[Component]]
Path = "testcase4_bs_txclassforwstring_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.WString_Service"
