[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforchar_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char_Device"

[[Component]]
Path = "testcase4_bs_txclassforchar_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char_Service"
