[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforint8_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Int8_Device"

[[Component]]
Path = "testcase4_bs_txclassforint8_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Int8_Service"
