[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforint64_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Int64_Device"

[[Component]]
Path = "testcase4_bs_txclassforint64_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Int64_Service"
