[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforunsignedlonglong_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.UnsignedLongLong_Device"

[[Component]]
Path = "testcase4_bs_txclassforunsignedlonglong_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.UnsignedLongLong_Service"
