[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforuint32_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Uint32_Device"

[[Component]]
Path = "testcase4_bs_txclassforuint32_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Uint32_Service"
