[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforshort_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Short_Device"

[[Component]]
Path = "testcase4_bs_txclassforshort_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Short_Service"
