[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforfloat_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Float_Device"

[[Component]]
Path = "testcase4_bs_txclassforfloat_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Float_Service"
