[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassfordouble_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Double_Device"

[[Component]]
Path = "testcase4_bs_txclassfordouble_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Double_Service"
