[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforunsignedshort_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.UnsignedShort_Device"

[[Component]]
Path = "testcase4_bs_txclassforunsignedshort_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.UnsignedShort_Service"
