[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforboolean_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Boolean_Device"

[[Component]]
Path = "testcase4_bs_txclassforboolean_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Boolean_Service"
