[Configuration]
Version = 100

[[Component]]
Path = "testcase4_vd_txclassforchar32_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char32_Device"

[[Component]]
Path = "testcase4_bs_txclassforchar32_tx.sdv"
Class = "Vehicle.Chassis.Vehicle.Char32_Service"
