[Configuration]
Version = 100

[[Component]]
Path = "can_dl_trunk.sdv"
Class = "CAN_data_link"
Name = "DataLink"

[[Component]]
Path = "trunk_vd_vehiclespeed_rx.sdv"
Class = "Vehicle.Speed_Device"
Name = "Vehicle.Speed_Device"

[[Component]]
Path = "trunk_vd_vehicletrunk_tx.sdv"
Class = "Vehicle.Body.Trunk_Device"
Name = "Vehicle.Body.Trunk_Device"


